# SPDX-FileCopyrightText: Copyright 2026 Anbiona
#
# SPDX-License-Identifier: Apache-2.0

name: build-gale
permissions: {}
on:
  schedule:
    - cron:
        "00 07 * * *" # build at 07:00 UTC every day
        # (1 hour after secureblue starts building)
  push:
    branches-ignore: # don't rebuild for dependabot
      - 'dependabot/**'
      - 'create-pull-request/**'
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  workflow_dispatch: # allow manually triggering builds
    inputs:
      clear-plan:
        description: 'Clear previous layer plan?'
        type: boolean
        required: true
        default: false


concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  gale-main:
    name: Build Gale
    permissions:
      contents: read # Needed to pull repo for building
      actions: read # Needed to read actions for provenance generation
      packages: write # Needed for publishing
      id-token: write # Needed for signing
    uses: ./.github/workflows/build-recipe.yml
    with:
      recipe: gale-main.yml
      rechunk: true # much more effecient images, experimental and will be deprecated
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}